# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: dgs-client

on:
  push:
    paths:
      - "dgs-client/**"
    branches: [ master ]
  pull_request:
    paths:
      - "dgs-client/**"  
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Build with Gradle
      run: |
        cd dgs-client
        chmod +x gradlew
        ./gradlew build

  