# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: dgs-webflux

on:
  push:
    paths:
      - "dgs-webflux/**"
    branches: [ master ]
  pull_request:
    paths:
      - "dgs-webflux/**"
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Setup Postgres in Docker 
      run: |
        docker-compose up -d postgres
        docker ps -a
    - name: Build with Maven
      run: |
        mvn -B -q clean verify -f dgs-webflux/pom.xml
        
 